# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: vivaswanth.github.io
name: vv
email: vivaswanth.k@gmail.com
disqus: vivaswanth
description: >- # this means to ignore newlines until "baseurl:"
  A collection of some useful tech stuff and randome thoughts about universe and everything.
#baseurl: "/_site" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
logo: 'assets/images/logo.png'
github_username:  vivaswanth
include: ["_pages"]
# Build settings
# theme: minima
remote_theme: wowthemesnet/mundana-theme-jekyll
plugins:
- jekyll-feed
- jekyll-remote-theme
- jekyll-sitemap
- jekyll-paginate
- jekyll-seo-tag
authors:
    vidyak:
      name:           Vidya Vivaswanth Katravulapalli
      site:           https://vivaswanth.github.io
      avatar:         assets/images/avatar1.jpg
      bio:            "Hi, I am VV, Full stack developer. I try to keep things simple and this blog is kinda experiment to preserve the various things I try to memorize but fail often. I hope you like it!"
      email:          vivaswanth.k@gmail.com

defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: vidyak
      avatar: assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge
paginate: 10
