---
title: vivaswanth.github.io
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: _posts
  values:
    layout: post
    author: vidyak
    avatar: assets/images/avatar1.jpg
- scope:
    path: _pages
  values:
    layout: page
name: vv
email: vivaswanth.k@gmail.com
disqus: vivaswanth
description: A collection of some useful tech stuff and randome thoughts about universe
  and everything.
url: ''
logo: assets/images/logo.png
github_username: vivaswanth
include:
- _pages
remote_theme: wowthemesnet/mundana-theme-jekyll
plugins:
- jekyll-feed
- jekyll-remote-theme
- jekyll-sitemap
- jekyll-paginate
- jekyll-seo-tag
authors:
  vidyak:
    name: Vidya Vivaswanth Katravulapalli
    site: https://vivaswanth.github.io
    avatar: assets/images/avatar1.jpg
    bio: Hi, I am VV, Full stack developer. I try to keep things simple and this blog
      is kinda experiment to preserve the various things I try to memorize but fail
      often. I hope you like it!
    email: vivaswanth.k@gmail.com
markdown: kramdown
highlighter: rouge
paginate: 10
